services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    ports:
      - "10000:80"

  db:
    image: postgres:15
    container_name: laravel_db
    ports:
      - "5433:5432"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: dpg-ct5n6pbqf0us7387vsmg-a
      DB_PORT: 5433
      DB_DATABASE: postgretsql_nutricion
      DB_USERNAME: postgretsql_nutricion_user
      DB_PASSWORD: IB3gMESBLN0NKrqmSH3YDHQ4uwF1AUzM
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel
    dns:
      - 8.8.8.8
      - 8.8.4.4

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: