services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=production
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-ct5n6pbqf0us7387vsmg-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_DATABASE=postgretsql_nutricion
      - DB_USERNAME=postgretsql_nutricion_user
      - DB_PASSWORD=IB3gMESBLN0NKrqmSH3YDHQ4uwF1AUzM


  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel: